"""empty message

Revision ID: 503000e239a5
Revises: 31a20bf26db1
Create Date: 2018-11-25 16:58:12.261406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503000e239a5'
down_revision = '31a20bf26db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('front_user',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('MAN', 'WOMEN', 'SECRET', 'UNKOWN', name='gender'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('front_user')
    # ### end Alembic commands ###
