"""empty message

Revision ID: 8e818ca15446
Revises: a13403a59324
Create Date: 2018-12-24 13:33:05.269704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e818ca15446'
down_revision = 'a13403a59324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Post_theme'), 'Post', ['theme'], unique=True)
    op.create_index(op.f('ix_area_name'), 'area', ['name'], unique=True)
    op.create_index(op.f('ix_front_user_telephone'), 'front_user', ['telephone'], unique=True)
    op.create_index(op.f('ix_front_user_username'), 'front_user', ['username'], unique=True)
    op.drop_index('telephone', table_name='front_user')
    op.drop_index('username', table_name='front_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'front_user', ['username'], unique=True)
    op.create_index('telephone', 'front_user', ['telephone'], unique=True)
    op.drop_index(op.f('ix_front_user_username'), table_name='front_user')
    op.drop_index(op.f('ix_front_user_telephone'), table_name='front_user')
    op.drop_index(op.f('ix_area_name'), table_name='area')
    op.drop_index(op.f('ix_Post_theme'), table_name='Post')
    # ### end Alembic commands ###
