"""empty message

Revision ID: 946970949a38
Revises: 612ffe8ab313
Create Date: 2018-11-12 16:39:46.021979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946970949a38'
down_revision = '612ffe8ab313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
