"""empty message

Revision ID: 9a3e0963f7ca
Revises: 9a9bdbbd784b
Create Date: 2018-12-04 15:26:08.335476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a3e0963f7ca'
down_revision = '9a9bdbbd784b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Carousel', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('Carousel', sa.Column('next_url', sa.String(length=256), nullable=False))
    op.add_column('Carousel', sa.Column('picture_url', sa.String(length=256), nullable=False))
    op.drop_column('Carousel', 'nexturl')
    op.drop_column('Carousel', 'pictureurl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Carousel', sa.Column('pictureurl', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('Carousel', sa.Column('nexturl', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('Carousel', 'picture_url')
    op.drop_column('Carousel', 'next_url')
    op.drop_column('Carousel', 'create_time')
    # ### end Alembic commands ###
