"""empty message

Revision ID: dcc6f0830233
Revises: 1ccee21c6996
Create Date: 2019-01-07 23:01:05.175916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc6f0830233'
down_revision = '1ccee21c6996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'locked')
    # ### end Alembic commands ###
